#!/usr/bin/python3

from datetime import date, timedelta, datetime
import argparse
import shutil
import copy

# Instantiate the parser
parser = argparse.ArgumentParser(description='Optional app description')
parser.add_argument('filename', type=str, help='input file name', default='test.g')
parser.add_argument('--debug', action='store_true', help='do not print diagnostics')
parser.add_argument('-i', '--interactive', action='store_true', help='interactive TUI mode')
args = parser.parse_args()


comment_char = '#'
option_char = '-'
break_char = ':'
extra_chars = '+-/^$@'
whitespace = ' '
# whitespace ="▒"

box_light_char="▒"
box_dark_char="█"
bg_light_char=" "
bg_dark_char="░"
# DEFAULT_GANTT_CHART_CHARACTER_TIMELINE="•"
# DEFAULT_GANTT_CHART_CHARACTER_TIMELINE="-"

f_date = None
header_modulo = 7
counter_string_modulo = True
modulo_shift = 0

gap = 1

color = {'PURPLE' : '\033[95m',
   'CYAN' : '\033[96m',
   'DARKCYAN' : '\033[36m',
   'BLUE' : '\033[94m',
   'GREEN' : '\033[92m',
   'YELLOW' : '\033[93m',
   'RED' : '\033[91m',
   'BOLD' : '\033[1m',
   'FAINT' : '\033[2m',
   'ITALIC' : '\033[3m',
   'UNDERLINE' : '\033[4m',
   'INVERSE' : '\033[7m',
   'BLINKING' : '\033[5m',
   'END' : '\033[0m'}

class entry(object):
    """Entry"""
    def __init__(self):
        self.key_string = ''
        self.type = 'data'
        self.duration = 0
        self.shift = 0
        self.highlight_len = 0
        self.value_string = ''

        self.start_date = None
        self.end_date = None

        self.start_ind = 0
        self.output_string = ''

        self.color = None
        

def format(style, string):
   return color[style] + string + color['END']

def bg_str(n, offset=0):
    s = ''
    for i in range(n):
        s += bg_light_char if (i + offset) % 2 else bg_dark_char
    return s

#######################################################################
# output header

def get_header_date(f_date, total_duration, header_modulo=7, modulo_shift=0):
    """A header with month, date, and dow, given starting date and duration

    :f_date: First date
    :total_duration: integer
    :header_modulo: how often to print
    :modulo_shift: shift of starting print
    :returns: header_month, header_date
    """
    header_month = ''
    header_date = ''

    header_month += ' ' * modulo_shift
    header_date += ' ' * modulo_shift

    for i in range(modulo_shift, total_duration, header_modulo):
        date = f_date + timedelta(days=i)

        counter_str = "{:%b}".format(date)
        entry_month = counter_str + ' ' * (header_modulo - len(counter_str))
        if len(header_month) + len(entry_month) > total_duration:
            break
        header_month += entry_month

        counter_str = "{:%d}".format(date)
        entry_date = counter_str + ' ' * (header_modulo - len(counter_str))
        if len(header_date) + len(entry_date) > total_duration:
            break
        header_date += entry_date

    return header_month, header_date

def get_hline_dow(f_date, total_duration, hl_today=True, hl_weekend=True, hl_modulo=False):
    """A header line with day of the week string with possible highlight of today's date, given initial date and duration

    :f_date: starting date
    :total_duration: duration of header in days
    :hl_today: highlight today's day
    :returns: string

    """
    hline = ''
    for i in range(total_duration):
        date = f_date + timedelta(days=i)

        counter_str = "{:%a}".format(date)[0]

        formatted_counter = format('FAINT', format('INVERSE', counter_str))

        if hl_today:
            if (date == datetime.today().date()):
                # highlight today's date
                # hline += format('BOLD', format('INVERSE', counter_str))
                # hline += format('BOLD', format('INVERSE', box_dark_char))
                # hline += format('BOLD', format('INVERSE', box_dark_char))
                # hline += format('BOLD', format('INVERSE', box_dark_char))
                formatted_counter = format('BLINKING', counter_str)

        if hl_weekend:
            if counter_str == 'S':
                formatted_counter = format('INVERSE', counter_str)

        if hl_modulo:
            if i % header_modulo == modulo_shift:
                # hline += '|'
                # hline += box_dark_char
                formatted_counter = format('INVERSE', counter_str)
            else:
                # hline += '-'
                # hline += box_light_char

                hline += format('FAINT', format('INVERSE', counter_str))

        hline += formatted_counter
    return hline


# print(format('BOLD', 'HeLlo there!'))

def get_header_hline_num(total_duration, header_modulo=7, modulo_shift=0):
    """TODO: Docstring for get_header_hline_num.

    :total_duration: TODO
    :header_modulo: TODO
    :modulo_shift: TODO
    :returns: TODO

    """
    header = ''
    header_count = 0
    for i in range(modulo_shift, total_duration, header_modulo):
        if counter_string_modulo:
            counter_str = str(header_count)
        else:
            counter_str = str(i)
        entry = counter_str + ' ' * (header_modulo - len(counter_str))
        if len(header) + len(entry) > total_duration:
            break
        header += entry
        header_count += 1

    hline = ''
    for i in range(total_duration):
        if i % header_modulo == modulo_shift:
            hline += box_dark_char
        else:
            hline += box_light_char

    return header, hline

#######################################################################
# read file

entries = []
with open(args.filename) as file:
    for i,line in enumerate(file):
        line = line.strip()
        if line.strip() == '':
            # empty line
            pass
        elif line[0] == comment_char:
            # comment line
            pass
        elif line[0] == option_char:
            if line.strip() == '---':
                e = entry()
                e.type = 'divider'
                e.key_string = '---'
                entries.append(e)
            elif line.strip() == '---h':
                e = entry()
                e.type = 'divider-header'
                e.key_string = '---h'
                entries.append(e)
            else:
                # option line
                chunks = line[1:].strip().split(break_char)
                option = chunks[0].strip().upper()
                val = chunks[1].strip()
                if args.debug:
                    print('Option:', option, val)
                if option == 'START':
                    if val == 'TODAY':
                        f_date = datetime.today().date()
                    else:
                        f_date = date.fromisoformat(val)
                    # print('f_date', f_date)
                if option == 'MODULO':
                    header_modulo = int(val)
                if option == 'LIGHT_CHAR':
                    box_light_char = str(val)
                if option == 'DARK_CHAR':
                    box_dark_char = str(val)
                if option == 'MODULO_SHIFT':  
                    modulo_shift = int(val)
        else:
            # data line
            if break_char in line:
                # line has break_char; valid data line
                e = entry()
                chunks = line.split(break_char)
                key = chunks[0].strip()
                e.key_string = key
                if chunks[1].strip() == '':
                    # heading line
                    e.type = 'heading'
                else:
                    # non-heading line
                    val = chunks[1].strip()
                    val_chunks = val.split(' ')
                    e.type = 'data'
                    # read other options specified
                    for ch in val_chunks:
                        if ch[0] in '+-':
                            e.shift = int(ch)
                        if ch[0] == '/':
                            e.highlight_len = int(ch[1:])
                        if ch[0] == '^':
                            e.start_date = date.fromisoformat(ch[1:])
                        if ch[0] == '$':
                            e.end_date = date.fromisoformat(ch[1:])
                        if ch[0] == '@':
                            e.color = ch[1:].strip().upper()
                        if (ch[0] not in extra_chars):
                            # no starting extra chars
                            if ch.strip().isdigit():
                                # is a number; treat at duration
                                e.duration = int(ch)
                            else:
                                # treat as a string; add it to the string list
                                e.value_string += ' ' + ch
                    # derive start_date and duration based on other info
                    if e.start_date is not None and e.end_date is not None:
                        e.duration = int((e.end_date - e.start_date).days) +1
                    if e.start_date is None and e.end_date is not None:
                        e.start_date = e.end_date - timedelta(days=e.duration)
                entries.append(e)
            else:
                # if args.debug:
                    print('Bad line:', i+1)

max_key_len = max( [len(e.key_string) for e in entries if e.type != 'heading'])

if args.debug:
    for i,e in enumerate(entries):
        print('e', e.__dict__)


def process_and_render(entries, f_date, header_modulo, modulo_shift, max_key_len):
    total_duration = 0
    running_duration = 0
    term_width = shutil.get_terminal_size().columns
    blank_len = max_key_len + 2 * gap
    for e in entries:
        if e.start_date is not None and f_date is not None:
            e.shift = (e.start_date - f_date).days - running_duration
        e.start_ind = running_duration + e.shift
        right_text_len = (1 + len(str(e.duration))) if e.duration else 0
        right_text_len += len(e.value_string)
        line_width = blank_len + e.start_ind + e.duration + right_text_len
        if e.start_date is not None and f_date is not None and \
           (e.start_ind < 0 or line_width > term_width):
            pass
        else:
            running_duration = e.start_ind + e.duration
        total_duration = max(running_duration, total_duration)

    blank = whitespace * blank_len

    if f_date is not None:
        header_month, header_date = get_header_date(f_date, total_duration, header_modulo=header_modulo, modulo_shift=modulo_shift)
        hline = get_hline_dow(f_date, total_duration, hl_today=True)
        header_top = blank + header_month + '\n' + blank + header_date + '\n' + blank + hline
        header_bottom = blank + hline + '\n' + blank + header_date + '\n' + blank + header_month
    else:
        header, hline = get_header_hline_num(total_duration, header_modulo=header_modulo, modulo_shift=modulo_shift)
        header_top = blank + header + '\n' + blank + hline
        header_bottom = blank + hline + '\n' + blank + header

    for e in entries:
        if e.type == 'heading':
            e.output_string = format('UNDERLINE', format('BOLD', e.key_string))
        elif e.type == 'divider':
            e.output_string = blank + '─' * total_duration
        elif e.type == 'divider-header':
            e.output_string = blank + hline
        elif e.start_ind < 0:
            if e.color is not None:
                col_key_string = format(e.color, e.key_string)
            else:
                col_key_string = e.key_string
            key_str = col_key_string + whitespace * (max_key_len - len(e.key_string) + gap)
            arrow_chars = '<--'
            arrow = ''
            for ch in arrow_chars:
                if e.color is not None:
                    arrow += format(e.color, ch)
                else:
                    arrow += ch
            val_str = arrow + bg_str(max(0, total_duration - 3), 3)
            if e.duration:
                dur_str = whitespace + str(e.duration)
                if e.color is not None:
                    dur_str = format(e.color, dur_str)
                val_str += dur_str
            if e.color is not None:
                col_value_string = format(e.color, e.value_string)
            else:
                col_value_string = e.value_string
            val_str += col_value_string
            e.output_string = key_str + whitespace * gap + val_str
        elif e.start_ind >= total_duration:
            if e.color is not None:
                col_key_string = format(e.color, e.key_string)
            else:
                col_key_string = e.key_string
            key_str = col_key_string + whitespace * (max_key_len - len(e.key_string) + gap)
            arrow_chars = '-->'
            arrow = ''
            for ch in arrow_chars:
                if e.color is not None:
                    arrow += format(e.color, ch)
                else:
                    arrow += ch
            val_str = bg_str(max(0, total_duration - 3)) + arrow
            if e.duration:
                dur_str = whitespace + str(e.duration)
                if e.color is not None:
                    dur_str = format(e.color, dur_str)
                val_str += dur_str
            if e.color is not None:
                col_value_string = format(e.color, e.value_string)
            else:
                col_value_string = e.value_string
            val_str += col_value_string
            e.output_string = key_str + whitespace * gap + val_str
        else:
            if e.color is not None:
                col_key_string = format(e.color, e.key_string)
            else:
                col_key_string = e.key_string
            key_str = col_key_string + whitespace * (max_key_len - len(e.key_string) + gap)
            val_str = bg_str(e.start_ind)
            remaining = total_duration - e.start_ind - e.duration
            if e.highlight_len:
                bar_str = box_light_char * e.highlight_len + box_dark_char * (e.duration - e.highlight_len)
            else:
                bar_str = box_dark_char * e.duration
            if e.color is not None:
                col_bar_str = format(e.color, bar_str)
            else:
                col_bar_str = bar_str
            val_str += col_bar_str
            if remaining > 0:
                val_str += bg_str(remaining, e.start_ind + e.duration)
            if e.duration:
                dur_str = whitespace + str(e.duration)
                if e.color is not None:
                    dur_str = format(e.color, dur_str)
                val_str += dur_str
            if e.color is not None:
                col_value_string = format(e.color, e.value_string)
            else:
                col_value_string = e.value_string
            val_str += col_value_string
            e.output_string = key_str + whitespace * gap + val_str

    return header_top, header_bottom, total_duration


#######################################################################
# TUI interactive mode

import re
import curses

def strip_ansi(s):
    return re.sub(r'\033\[[0-9;]*m', '', s)

def edit_entry(stdscr, e, f_date):
    fields = [
        ('key', e.key_string),
        ('duration', str(e.duration)),
        ('shift', str(e.shift)),
        ('value', e.value_string.strip()),
        ('color', e.color or ''),
    ]
    if e.start_date:
        fields.append(('start_date', e.start_date.isoformat()))
    if e.end_date:
        fields.append(('end_date', e.end_date.isoformat()))

    height, width = stdscr.getmaxyx()
    win_h = len(fields) + 4
    win_w = min(60, width - 4)
    win_y = (height - win_h) // 2
    win_x = (width - win_w) // 2

    win = curses.newwin(win_h, win_w, win_y, win_x)
    win.box()
    win.addstr(0, 2, " Edit entry (Tab/Shift+Tab: next field, Esc: cancel, Enter: save) ")

    cur_field = 0
    vals = [v for _, v in fields]
    while True:
        for i, (name, _) in enumerate(fields):
            y = 2 + i
            label = f" {name}: "
            win.addstr(y, 2, label)
            val = vals[i]
            if i == cur_field:
                win.attron(curses.A_REVERSE)
                win.addstr(y, 2 + len(label), val + ' ' * max(0, win_w - 4 - len(label) - len(val)))
                win.attroff(curses.A_REVERSE)
            else:
                win.addstr(y, 2 + len(label), val + ' ' * max(0, win_w - 4 - len(label) - len(val)))
        win.refresh()

        key = stdscr.getch()
        if key == 27:  # Esc
            return False
        elif key == ord('\n') or key == ord('\r'):
            break
        elif key == ord('\t'):
            cur_field = (cur_field + 1) % len(fields)
        elif key == curses.KEY_BTAB:
            cur_field = (cur_field - 1) % len(fields)
        elif key == curses.KEY_UP:
            cur_field = (cur_field - 1) % len(fields)
        elif key == curses.KEY_DOWN:
            cur_field = (cur_field + 1) % len(fields)
        elif key in [curses.KEY_BACKSPACE, 127, 8]:
            vals[cur_field] = vals[cur_field][:-1]
        elif 32 <= key <= 126:
            vals[cur_field] += chr(key)

    # Apply edited values
    e.key_string = vals[0]
    try:
        e.duration = int(vals[1]) if vals[1] else 0
    except ValueError:
        pass
    try:
        e.shift = int(vals[2]) if vals[2] else 0
    except ValueError:
        pass
    e.value_string = ' ' + vals[3] if vals[3] else ''
    e.color = vals[4].upper() if vals[4] else None

    field_idx = 5
    if e.start_date is not None or (field_idx < len(vals) and vals[field_idx]):
        if field_idx < len(vals) and vals[field_idx]:
            try:
                e.start_date = date.fromisoformat(vals[field_idx])
            except ValueError:
                pass
        field_idx += 1
    else:
        if field_idx < len(fields):
            field_idx += 1
    if e.end_date is not None or (field_idx < len(vals) and vals[field_idx]):
        if field_idx < len(vals) and vals[field_idx]:
            try:
                e.end_date = date.fromisoformat(vals[field_idx])
            except ValueError:
                pass

    del win
    return True


def serialize_entry(e):
    if e.type == 'divider':
        return '---'
    if e.type == 'divider-header':
        return '---h'
    if e.type == 'heading':
        return e.key_string + break_char
    parts = []
    if e.duration:
        parts.append(str(e.duration))
    if e.shift:
        parts.append(f'{e.shift:+d}')
    if e.highlight_len:
        parts.append(f'/{e.highlight_len}')
    if e.start_date:
        parts.append(f'^{e.start_date.isoformat()}')
    if e.end_date:
        parts.append(f'${e.end_date.isoformat()}')
    if e.color:
        parts.append(f'@{e.color}')
    if e.value_string:
        parts.append(e.value_string.strip())
    return f'{e.key_string}{break_char} {" ".join(parts)}'


def run_tui(stdscr, entries, f_date, header_modulo, modulo_shift, max_key_len):
    curses.curs_set(0)
    ansi_pair = {
        '91': 1, '92': 2, '93': 3, '94': 4, '96': 5, '95': 6, '36': 5,
    }
    ansi_attr = {
        '1': curses.A_BOLD, '2': curses.A_DIM, '4': curses.A_UNDERLINE, '7': curses.A_REVERSE,
    }
    bright_codes = {'91', '92', '93', '94', '95', '96'}

    def render_line(y, x, raw, width):
        i = 0
        pair = 0
        attrs = 0
        while i < len(raw) and x < width:
            if raw[i] == '\033' and i + 1 < len(raw) and raw[i + 1] == '[':
                j = i + 2
                while j < len(raw) and raw[j] != 'm':
                    j += 1
                if j < len(raw):
                    codes = raw[i + 2:j].split(';')
                    for code in codes:
                        if code == '0':
                            pair = 0
                            attrs = 0
                        elif code in ansi_pair:
                            pair = ansi_pair[code]
                            if code in bright_codes:
                                attrs |= curses.A_BOLD
                            else:
                                attrs &= ~curses.A_BOLD
                        elif code in ansi_attr:
                            attrs |= ansi_attr[code]
                    i = j + 1
                    continue
            if ord(raw[i]) >= 32:
                if pair:
                    stdscr.attrset(curses.color_pair(pair) | attrs)
                elif attrs:
                    stdscr.attrset(attrs)
                else:
                    stdscr.attrset(0)
                stdscr.addch(y, x, raw[i])
                x += 1
            i += 1
        stdscr.attrset(0)

    if curses.has_colors():
        curses.start_color()
        curses.use_default_colors()
        curses.init_pair(1, curses.COLOR_RED, -1)
        curses.init_pair(2, curses.COLOR_GREEN, -1)
        curses.init_pair(3, curses.COLOR_YELLOW, -1)
        curses.init_pair(4, curses.COLOR_BLUE, -1)
        curses.init_pair(5, curses.COLOR_CYAN, -1)
        curses.init_pair(6, curses.COLOR_MAGENTA, -1)

    selected = 0
    lines_cache = []
    header_lines = 0
    undo_stack = []
    status_msg = ''

    def push_undo():
        undo_stack.append(copy.deepcopy(entries))

    def save_file():
        with open(args.filename, 'w') as f:
            f.write('# Generated by gantt-py interactive mode\n')
            if f_date:
                f.write(f'- START: {f_date.isoformat()}\n')
            if header_modulo != 7:
                f.write(f'- MODULO: {header_modulo}\n')
            if modulo_shift != 0:
                f.write(f'- MODULO_SHIFT: {modulo_shift}\n')
            if break_char != ':':
                f.write(f'- BREAK_CHAR: {break_char}\n')
            f.write('\n')
            for e in entries:
                f.write(serialize_entry(e) + '\n')

    def build_lines():
        nonlocal lines_cache, header_lines
        header_top, header_bottom, _ = process_and_render(
            entries, f_date, header_modulo, modulo_shift, max_key_len
        )
        header_lines = header_top.count('\n') + 1
        lines_cache = []
        for line in header_top.split('\n'):
            lines_cache.append(line)
        for e in entries:
            lines_cache.append(e.output_string)
        for line in header_bottom.split('\n'):
            lines_cache.append(line)

    build_lines()

    while True:
        height, width = stdscr.getmaxyx()
        stdscr.clear()

        display_lines = len(lines_cache)
        max_scroll = max(0, display_lines - (height - 1))
        scroll = max(0, selected - (height - 1) // 2)
        scroll = min(scroll, max_scroll)
        selected_global = header_lines + selected

        for i in range(height - 1):
            idx = i + scroll
            if idx >= display_lines:
                break
            raw = lines_cache[idx]
            if idx == selected_global:
                stdscr.attron(curses.A_REVERSE)
                stdscr.addstr(i, 0, strip_ansi(raw)[:width - 1])
                stdscr.attroff(curses.A_REVERSE)
            elif idx == 0 or idx == display_lines - 1:
                stdscr.attron(curses.A_DIM)
                stdscr.addstr(i, 0, strip_ansi(raw)[:width - 1])
                stdscr.attroff(curses.A_DIM)
            else:
                render_line(i, 0, raw, width - 1)

        mode = status_msg if status_msg else 'VIEW'
        status_msg = ''
        status = f" {mode}  |  j/k: navigate  i: edit  s: save  u: undo  q: quit  |  entry {selected+1}/{len(entries)}"
        stdscr.attron(curses.A_REVERSE)
        stdscr.addstr(height - 1, 0, status + ' ' * max(0, width - 1 - len(status)))
        stdscr.attroff(curses.A_REVERSE)

        key = stdscr.getch()
        if key == ord('q'):
            break
        elif key == ord('j') or key == curses.KEY_DOWN:
            selected = min(selected + 1, len(entries) - 1)
        elif key == ord('k') or key == curses.KEY_UP:
            selected = max(selected - 1, 0)
        elif key == ord('g'):
            selected = 0
        elif key == ord('G'):
            selected = len(entries) - 1
        elif key == ord('i'):
            e = entries[selected]
            push_undo()
            curses.curs_set(1)
            changed = edit_entry(stdscr, e, f_date)
            curses.curs_set(0)
            if changed:
                build_lines()
            stdscr.clear()
            stdscr.refresh()
        elif key == ord('o'):
            push_undo()
            new_e = entry()
            new_e.key_string = 'new'
            new_e.duration = 1
            entries.insert(selected + 1, new_e)
            selected += 1
            build_lines()
        elif key == ord('O'):
            push_undo()
            new_e = entry()
            new_e.key_string = 'new'
            new_e.duration = 1
            entries.insert(selected, new_e)
            build_lines()
        elif key == ord('d'):
            nkey = stdscr.getch()
            if nkey == ord('d') and len(entries) > 1:
                push_undo()
                del entries[selected]
                if selected >= len(entries):
                    selected = len(entries) - 1
                build_lines()
        elif key == ord('s'):
            save_file()
            status_msg = 'SAVED'
        elif key == ord('u'):
            if undo_stack:
                entries[:] = copy.deepcopy(undo_stack.pop())
                selected = min(selected, len(entries) - 1)
                build_lines()
                status_msg = 'UNDO'
        elif key == ord('r'):
            build_lines()
        elif key == ord('n'):
            build_lines()
        elif key == ord('h'):
            pass
        elif key == ord('l'):
            pass


#######################################################################
# Main

if args.interactive:
    curses.wrapper(run_tui, entries, f_date, header_modulo, modulo_shift, max_key_len)
else:
    header_top, header_bottom, _ = process_and_render(
        entries, f_date, header_modulo, modulo_shift, max_key_len
    )
    print(header_top)
    for e in entries:
        print(e.output_string)
    print(header_bottom)


