#!/usr/bin/python3

from datetime import date, timedelta, datetime
import argparse
import shutil

# Instantiate the parser
parser = argparse.ArgumentParser(description='Optional app description')
parser.add_argument('filename', type=str, help='input file name', default='test.g')
parser.add_argument('--debug', action='store_true', help='do not print diagnostics')
args = parser.parse_args()


comment_char = '#'
option_char = '-'
break_char = ':'
extra_chars = '+-/^$@'
whitespace = ' '
# whitespace ="▒"

box_light_char="▒"
box_dark_char="█"
bg_light_char=" "
bg_dark_char="░"
# DEFAULT_GANTT_CHART_CHARACTER_TIMELINE="•"
# DEFAULT_GANTT_CHART_CHARACTER_TIMELINE="-"

f_date = None
header_modulo = 7
counter_string_modulo = True
modulo_shift = 0

gap = 1

color = {'PURPLE' : '\033[95m',
   'CYAN' : '\033[96m',
   'DARKCYAN' : '\033[36m',
   'BLUE' : '\033[94m',
   'GREEN' : '\033[92m',
   'YELLOW' : '\033[93m',
   'RED' : '\033[91m',
   'BOLD' : '\033[1m',
   'FAINT' : '\033[2m',
   'ITALIC' : '\033[3m',
   'UNDERLINE' : '\033[4m',
   'INVERSE' : '\033[7m',
   'BLINKING' : '\033[5m',
   'END' : '\033[0m'}

class entry(object):
    """Entry"""
    def __init__(self):
        self.key_string = ''
        self.type = 'data'
        self.duration = 0
        self.shift = 0
        self.highlight_len = 0
        self.value_string = ''

        self.start_date = None
        self.end_date = None

        self.start_ind = 0
        self.output_string = ''

        self.color = None
        

def format(style, string):
   return color[style] + string + color['END']

def bg_str(n, offset=0):
    s = ''
    for i in range(n):
        s += bg_light_char if (i + offset) % 2 else bg_dark_char
    return s

#######################################################################
# output header

def get_header_date(f_date, total_duration, header_modulo=7, modulo_shift=0):
    """A header with month, date, and dow, given starting date and duration

    :f_date: First date
    :total_duration: integer
    :header_modulo: how often to print
    :modulo_shift: shift of starting print
    :returns: header_month, header_date
    """
    header_month = ''
    header_date = ''

    header_month += ' ' * modulo_shift
    header_date += ' ' * modulo_shift

    for i in range(modulo_shift, total_duration, header_modulo):
        date = f_date + timedelta(days=i)

        counter_str = "{:%b}".format(date)
        entry_month = counter_str + ' ' * (header_modulo - len(counter_str))
        if len(header_month) + len(entry_month) > total_duration:
            break
        header_month += entry_month

        counter_str = "{:%d}".format(date)
        entry_date = counter_str + ' ' * (header_modulo - len(counter_str))
        if len(header_date) + len(entry_date) > total_duration:
            break
        header_date += entry_date

    return header_month, header_date

def get_hline_dow(f_date, total_duration, hl_today=True, hl_weekend=True, hl_modulo=False):
    """A header line with day of the week string with possible highlight of today's date, given initial date and duration

    :f_date: starting date
    :total_duration: duration of header in days
    :hl_today: highlight today's day
    :returns: string

    """
    hline = ''
    for i in range(total_duration):
        date = f_date + timedelta(days=i)

        counter_str = "{:%a}".format(date)[0]

        formatted_counter = format('FAINT', format('INVERSE', counter_str))

        if hl_today:
            if (date == datetime.today().date()):
                # highlight today's date
                # hline += format('BOLD', format('INVERSE', counter_str))
                # hline += format('BOLD', format('INVERSE', box_dark_char))
                # hline += format('BOLD', format('INVERSE', box_dark_char))
                # hline += format('BOLD', format('INVERSE', box_dark_char))
                formatted_counter = format('BLINKING', counter_str)

        if hl_weekend:
            if counter_str == 'S':
                formatted_counter = format('INVERSE', counter_str)

        if hl_modulo:
            if i % header_modulo == modulo_shift:
                # hline += '|'
                # hline += box_dark_char
                formatted_counter = format('INVERSE', counter_str)
            else:
                # hline += '-'
                # hline += box_light_char

                hline += format('FAINT', format('INVERSE', counter_str))

        hline += formatted_counter
    return hline


# print(format('BOLD', 'HeLlo there!'))

def get_header_hline_num(total_duration, header_modulo=7, modulo_shift=0):
    """TODO: Docstring for get_header_hline_num.

    :total_duration: TODO
    :header_modulo: TODO
    :modulo_shift: TODO
    :returns: TODO

    """
    header = ''
    header_count = 0
    for i in range(modulo_shift, total_duration, header_modulo):
        if counter_string_modulo:
            counter_str = str(header_count)
        else:
            counter_str = str(i)
        entry = counter_str + ' ' * (header_modulo - len(counter_str))
        if len(header) + len(entry) > total_duration:
            break
        header += entry
        header_count += 1

    hline = ''
    for i in range(total_duration):
        if i % header_modulo == modulo_shift:
            hline += box_dark_char
        else:
            hline += box_light_char

    return header, hline

#######################################################################
# read file

entries = []
with open(args.filename) as file:
    for i,line in enumerate(file):
        line = line.strip()
        if line.strip() == '':
            # empty line
            pass
        elif line[0] == comment_char:
            # comment line
            pass
        elif line[0] == option_char:
            if line.strip() == '---':
                e = entry()
                e.type = 'divider'
                entries.append(e)
            elif line.strip() == '---h':
                e = entry()
                e.type = 'divider-header'
                entries.append(e)
            else:
                # option line
                chunks = line[1:].strip().split(break_char)
                option = chunks[0].strip().upper()
                val = chunks[1].strip()
                if args.debug:
                    print('Option:', option, val)
                if option == 'START':
                    if val == 'TODAY':
                        f_date = datetime.today().date()
                    else:
                        f_date = date.fromisoformat(val)
                    # print('f_date', f_date)
                if option == 'MODULO':
                    header_modulo = int(val)
                if option == 'LIGHT_CHAR':
                    box_light_char = str(val)
                if option == 'DARK_CHAR':
                    box_dark_char = str(val)
                if option == 'MODULO_SHIFT':  
                    modulo_shift = int(val)
        else:
            # data line
            if break_char in line:
                # line has break_char; valid data line
                e = entry()
                chunks = line.split(break_char)
                key = chunks[0].strip()
                e.key_string = key
                if chunks[1].strip() == '':
                    # heading line
                    e.type = 'heading'
                else:
                    # non-heading line
                    val = chunks[1].strip()
                    val_chunks = val.split(' ')
                    e.type = 'data'
                    # read other options specified
                    for ch in val_chunks:
                        if ch[0] in '+-':
                            e.shift = int(ch)
                        if ch[0] == '/':
                            e.highlight_len = int(ch[1:])
                        if ch[0] == '^':
                            e.start_date = date.fromisoformat(ch[1:])
                        if ch[0] == '$':
                            e.end_date = date.fromisoformat(ch[1:])
                        if ch[0] == '@':
                            e.color = ch[1:].strip().upper()
                        if (ch[0] not in extra_chars):
                            # no starting extra chars
                            if ch.strip().isdigit():
                                # is a number; treat at duration
                                e.duration = int(ch)
                            else:
                                # treat as a string; add it to the string list
                                e.value_string += ' ' + ch
                    # derive start_date and duration based on other info
                    if e.start_date is not None and e.end_date is not None:
                        e.duration = int((e.end_date - e.start_date).days) +1
                    if e.start_date is None and e.end_date is not None:
                        e.start_date = e.end_date - timedelta(days=e.duration)
                entries.append(e)
            else:
                # if args.debug:
                    print('Bad line:', i+1)
#######################################################################
# Processing

# max key string length
max_key_len = max( [len(e.key_string) for e in entries if e.type != 'heading'])

# computing starting index of each bar
total_duration = 0
running_duration = 0
term_width = shutil.get_terminal_size().columns
blank_len = max_key_len + 2 * gap
for i,e in enumerate(entries):
    if e.start_date is not None and f_date is not None:
        e.shift = (e.start_date - f_date).days - running_duration

    e.start_ind = running_duration + e.shift

    right_text_len = (1 + len(str(e.duration))) if e.duration else 0
    right_text_len += len(e.value_string)
    line_width = blank_len + e.start_ind + e.duration + right_text_len

    if e.start_date is not None and f_date is not None and \
       (e.start_ind < 0 or line_width > term_width):
        pass
    else:
        running_duration = e.start_ind + e.duration

    # need to save historical max duration
    total_duration = max(running_duration, total_duration)

blank = whitespace * blank_len

if args.debug:
    for i,e in enumerate(entries):
        print('e', e.__dict__)
    print('total_duration', total_duration)

#######################################################################
# Output

if f_date is not None:
    header_month, header_date =  get_header_date(f_date, total_duration, header_modulo=header_modulo, modulo_shift=modulo_shift)
    hline = get_hline_dow(f_date, total_duration, hl_today=True)

    header_top = blank + header_month + '\n' + blank + header_date + '\n' + blank + hline
    header_bottom =  blank + hline + '\n' + blank + header_date + '\n' + blank + header_month

else:

    header, hline = get_header_hline_num(total_duration, header_modulo=header_modulo, modulo_shift=modulo_shift)

    header_top = blank + header + '\n' + blank + hline
    header_bottom =  blank + hline + '\n' + blank + header 

#######################################################################
# output string construction
for i,e in enumerate(entries):
    if e.type == 'heading':
        e.output_string = format('UNDERLINE', format('BOLD', e.key_string))
    elif e.type == 'divider':
        # e.output_string = blank + '-' * total_duration
        e.output_string = blank + '─' * total_duration
        # e.output_string = blank + hline
    elif e.type == 'divider-header':
        # e.output_string = blank + '-' * total_duration
        e.output_string = blank + hline

    elif e.start_ind < 0:
        if e.color is not None:
            col_key_string = format(e.color, e.key_string)
        else:
            col_key_string = e.key_string
        key_str = col_key_string + whitespace * (max_key_len - len(e.key_string) + gap)
        arrow_chars = '<--'
        arrow = ''
        for i, ch in enumerate(arrow_chars):
            pos = i
            bg_ch = bg_dark_char if pos % 2 == 0 else bg_light_char
            if e.color is not None:
                if bg_ch == bg_light_char:
                    arrow += format(e.color, ch)
                else:
                    arrow += format(e.color, bg_ch)
            else:
                arrow += ch if bg_ch == bg_light_char else bg_ch
        val_str = arrow + bg_str(max(0, total_duration - 3), 3)
        if e.duration:
            dur_str = whitespace + str(e.duration)
            if e.color is not None:
                dur_str = format(e.color, dur_str)
            val_str += dur_str
        if e.color is not None:
            col_value_string = format(e.color, e.value_string)
        else:
            col_value_string = e.value_string
        val_str += col_value_string
        e.output_string = key_str + whitespace * gap + val_str
    elif e.start_ind >= total_duration:
        if e.color is not None:
            col_key_string = format(e.color, e.key_string)
        else:
            col_key_string = e.key_string
        key_str = col_key_string + whitespace * (max_key_len - len(e.key_string) + gap)
        arrow_chars = '-->'
        arrow = ''
        for i, ch in enumerate(arrow_chars):
            pos = total_duration - 3 + i
            bg_ch = bg_dark_char if pos % 2 == 0 else bg_light_char
            if e.color is not None:
                if bg_ch == bg_light_char:
                    arrow += format(e.color, ch)
                else:
                    arrow += format(e.color, bg_ch)
            else:
                arrow += ch if bg_ch == bg_light_char else bg_ch
        val_str = bg_str(max(0, total_duration - 3)) + arrow
        if e.duration:
            dur_str = whitespace + str(e.duration)
            if e.color is not None:
                dur_str = format(e.color, dur_str)
            val_str += dur_str
        if e.color is not None:
            col_value_string = format(e.color, e.value_string)
        else:
            col_value_string = e.value_string
        val_str += col_value_string
        e.output_string = key_str + whitespace * gap + val_str
    else:
        if e.color is not None:
            col_key_string = format(e.color, e.key_string)
        else:
            col_key_string = e.key_string

        key_str = col_key_string + whitespace * (max_key_len - len(e.key_string) + gap)

        val_str = bg_str(e.start_ind)
        remaining = total_duration - e.start_ind - e.duration

        if e.highlight_len:
            bar_str = box_light_char * e.highlight_len + box_dark_char * (e.duration - e.highlight_len)
        else:
            bar_str = box_dark_char * e.duration

        if e.color is not None:
            col_bar_str = format(e.color, bar_str)
        else:
            col_bar_str = bar_str

        val_str += col_bar_str
        if remaining > 0:
            val_str += bg_str(remaining, e.start_ind + e.duration)
        if e.duration:
            dur_str = whitespace + str(e.duration)
            if e.color is not None:
                dur_str = format(e.color, dur_str)
            val_str += dur_str

        if e.color is not None:
            col_value_string = format(e.color, e.value_string)
        else:
            col_value_string = e.value_string
        val_str += col_value_string

        e.output_string = key_str + whitespace * gap + val_str



# final output
print(header_top)
for i,e in enumerate(entries):
    print(e.output_string)
print(header_bottom)


