# Generated by gantt-py interactive mode
- START: 2026-03-02

Testing:
Test Live View: 15
Test Live View again: 15 -8 /3 ^2026-03-09
More testing: done
Attendance Blocks Tab:
Design UX: 8
Implement Listings: blocked
Implement Details: 8 -3 @RED
new: 2 @BLUE
Directory-Attendance Integration:
Design UX: done
Implement Viewing: 10 -3 @GREEN
This: 5
That: 8 -21 /2 ^2026-03-30 @BLUE
Due: 1 +48 ^2026-05-25 @RED
---
10pager:
Due: 1 -8 ^2026-03-30 @RED
Design UX: done more
More Viewing: 13 -1 @YELLOW
---
By date: 39 -30 /10 ^2026-03-13 $2026-04-20 @CYAN
By enddate: 8 -45 ^2026-03-07 $2026-03-14 @YELLOW
