# Generated by gantt-py interactive mode
- START: 2026-03-02

Testing:
Test Live View: 15
Test Live View again: 15  /3 ^2026-03-09
More testing: done
Attendance Blocks Tab:
Design UX: 8
Implement Listings: blocked
Implement Details: 8  @RED
new: 2 @BLUE
Directory-Attendance Integration:
Design UX: done
Implement Viewing: 10  @GREEN
This: 5
That: 8  /2 ^2026-03-30 @BLUE
Due: 1  ^2026-05-25 @RED
---
10pager:
Due: 1  ^2026-03-30 @RED
Design UX: done more
More Viewing: 13 -1 @YELLOW
---
By date: 39  /10 ^2026-03-13 $2026-04-20 @CYAN
By enddate: 8  ^2026-03-07 $2026-03-14 @YELLOW
