# Generated by gantt-py interactive mode

Testing:
Test Live View: 4
Attendance Blocks Tab:
Design UX: 6 /1
new: 1
Implement Listings: @RED blocked
Implement Details: 24 /20
Directory-Attendance Integration:
Design UX: done
Implement Viewing: 24 /8
